### ISSUE TITLE
Response with unknown request ID from X.X.X.X. Consider increasing timeouts (5083 ms old?).

### ISSUE THREAD

**Issue by sagax** [calmh/node-snmp-native#54]
node **v7.2.1**
npm **3.10.10**
snmp-native  **1.0.21** in package.json

use snmp-native like this
```javascript
            session: new snmp.Session({
              host: host,
              community: community
            }),

```
after
```javascript
              session.get({
                oid: oid
              }, function(err, data) {
                var value;
                if (err) {
                  return;
                }
                if (data) {
                  value = data[0].value;
                  daemon.write_stat_data(value, host, tags, type, os);
                }
              });
```

**Comment by bangert** [comment]
Hi @sagax, 

could you state what the problem is?
The error message means that the library has received an old response - so the callback for the request that the response belongs to has already been fired with a Timeout response. If you increase the timeouts it would be received correctly...

Hope this helps.
kind regards
Thilo

**Comment by sagax** [comment]
I'll will try to increase the timeouts, thanks!
